### ISSUE TITLE
Alert link rating role when links go above specified threshold 

### ISSUE THREAD

**Issue by thunderysteak** [posttwo/fjdiscordapp#23]
Same thing as sfw rating but for links,but with links only and it mentions the link moderator role when it goes above 30 or 40 links. 
Discuss with Ben the alert threshold and the approval of the addition to the bot.

**Comment by posttwo** [comment]
https://github.com/posttwo/fjdiscordapp/blob/plstestme/app/Console/Kernel.php#L82

Good luck :)
